DROP TABLE IF EXISTS TEAMMEMBERS;
  
CREATE TABLE TEAMMEMBERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  lastName VARCHAR(250) NOT NULL,
  rol VARCHAR(250) DEFAULT NULL
);